[2025-07-19T16:03:25.219+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:02:18.427943+00:00 [queued]>
[2025-07-19T16:03:25.221+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:02:18.427943+00:00 [queued]>
[2025-07-19T16:03:25.222+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-07-19T16:03:25.225+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 16:02:18.427943+00:00
[2025-07-19T16:03:25.229+0000] {standard_task_runner.py:60} INFO - Started process 211 to run task
[2025-07-19T16:03:25.231+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T16:02:18.427943+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpvvv8cz0w']
[2025-07-19T16:03:25.231+0000] {standard_task_runner.py:88} INFO - Job 166: Subtask validate_features
[2025-07-19T16:03:25.247+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:02:18.427943+00:00 [running]> on host 2eec98a4066b
[2025-07-19T16:03:25.275+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T16:02:18.427943+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T16:02:18.427943+00:00'
[2025-07-19T16:03:25.294+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T16:03:25.295+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T16:03:25.295+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:03:25.296+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:03:25.312+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T16:03:25.312+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T16:03:25.312+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:03:25.312+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:03:25.313+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:03:25.365+0000] {validator.py:1461} INFO - 	12 expectation(s) included in expectation_suite.
[2025-07-19T16:03:25.433+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T16:03:25.433+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T16:03:25.433+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 4686.37it/s]
[2025-07-19T16:03:25.447+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 145.31it/s] 
[2025-07-19T16:03:25.447+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 214.41it/s]
[2025-07-19T16:03:25.460+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 110.90it/s]
[2025-07-19T16:03:25.463+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 527.18it/s]
[2025-07-19T16:03:25.474+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 389.15it/s]
[2025-07-19T16:03:25.485+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1184.87it/s]
[2025-07-19T16:03:25.489+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1098.03it/s]
[2025-07-19T16:03:25.489+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1095.65it/s]
[2025-07-19T16:03:25.490+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 1093.19it/s]
[2025-07-19T16:03:25.626+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 99, in validate_features
    raise ValueError("❌ Feature DQ checks failed")
ValueError: ❌ Feature DQ checks failed
[2025-07-19T16:03:25.630+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T160218, start_date=20250719T160325, end_date=20250719T160325
[2025-07-19T16:03:25.637+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 166 for task validate_features (❌ Feature DQ checks failed; 211)
[2025-07-19T16:03:25.666+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T16:03:25.673+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
