[2025-07-19T16:11:28.719+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:11:20.284681+00:00 [queued]>
[2025-07-19T16:11:28.722+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:11:20.284681+00:00 [queued]>
[2025-07-19T16:11:28.722+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-19T16:11:28.727+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): validate_features> on 2025-07-19 16:11:20.284681+00:00
[2025-07-19T16:11:28.732+0000] {standard_task_runner.py:60} INFO - Started process 140 to run task
[2025-07-19T16:11:28.735+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'validate_features', 'manual__2025-07-19T16:11:20.284681+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmp21tzy2jz']
[2025-07-19T16:11:28.735+0000] {standard_task_runner.py:88} INFO - Job 177: Subtask validate_features
[2025-07-19T16:11:28.759+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.validate_features manual__2025-07-19T16:11:20.284681+00:00 [running]> on host d41c0535c8b8
[2025-07-19T16:11:28.797+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='validate_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T16:11:20.284681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T16:11:20.284681+00:00'
[2025-07-19T16:11:28.822+0000] {file_data_context.py:222} INFO - FileDataContext loading fluent config
[2025-07-19T16:11:28.824+0000] {config.py:187} INFO - Loading 'datasources' ->
[{'assets': [...], 'name': 'local_pandas', 'type': 'pandas'}]
[2025-07-19T16:11:28.825+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:11:28.825+0000] {fluent_base_model.py:276} INFO - _PandasDataAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:11:28.840+0000] {abstract_data_context.py:5515} INFO - Loaded 'local_pandas' from fluent config
[2025-07-19T16:11:28.842+0000] {file_data_context.py:174} INFO - Saving 1 Fluent Datasources to /opt/***/gx/great_expectations.yml
[2025-07-19T16:11:28.844+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:11:28.844+0000] {fluent_base_model.py:276} INFO - DataFrameAsset.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:11:28.845+0000] {fluent_base_model.py:276} INFO - PandasDatasource.dict() - missing `config_provider`, skipping config substitution
[2025-07-19T16:11:28.895+0000] {validator.py:1461} INFO - 	12 expectation(s) included in expectation_suite.
[2025-07-19T16:11:28.970+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T16:11:28.970+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   0%|          | 0/62 [00:00<?, ?it/s]
[2025-07-19T16:11:28.971+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 3425.32it/s]
[2025-07-19T16:11:28.990+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   3%|3         | 2/62 [00:00<00:00, 100.64it/s] 
[2025-07-19T16:11:28.991+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 146.82it/s]
[2025-07-19T16:11:29.008+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:   5%|4         | 3/62 [00:00<00:00, 79.46it/s] 
[2025-07-19T16:11:29.018+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 337.44it/s]
[2025-07-19T16:11:29.039+0000] {logging_mixin.py:188} WARNING - Calculating Metrics:  26%|##5       | 16/62 [00:00<00:00, 232.12it/s]
[2025-07-19T16:11:29.058+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 709.83it/s]
[2025-07-19T16:11:29.069+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 631.70it/s]
[2025-07-19T16:11:29.069+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 628.19it/s]
[2025-07-19T16:11:29.069+0000] {logging_mixin.py:188} WARNING - Calculating Metrics: 100%|##########| 62/62 [00:00<00:00, 626.26it/s]
[2025-07-19T16:11:29.265+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 99, in validate_features
    raise ValueError("❌ Feature DQ checks failed")
ValueError: ❌ Feature DQ checks failed
[2025-07-19T16:11:29.271+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=validate_features, execution_date=20250719T161120, start_date=20250719T161128, end_date=20250719T161129
[2025-07-19T16:11:29.276+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 177 for task validate_features (❌ Feature DQ checks failed; 140)
[2025-07-19T16:11:29.285+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T16:11:29.297+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
