[2025-07-19T13:26:05.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.extract_curated manual__2025-07-19T13:25:27.902476+00:00 [queued]>
[2025-07-19T13:26:05.569+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.extract_curated manual__2025-07-19T13:25:27.902476+00:00 [queued]>
[2025-07-19T13:26:05.570+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-07-19T13:26:05.573+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_curated> on 2025-07-19 13:25:27.902476+00:00
[2025-07-19T13:26:05.577+0000] {standard_task_runner.py:60} INFO - Started process 364 to run task
[2025-07-19T13:26:05.579+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'extract_curated', 'manual__2025-07-19T13:25:27.902476+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpbvfj94cy']
[2025-07-19T13:26:05.579+0000] {standard_task_runner.py:88} INFO - Job 71: Subtask extract_curated
[2025-07-19T13:26:05.596+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.extract_curated manual__2025-07-19T13:25:27.902476+00:00 [running]> on host e05da308c0da
[2025-07-19T13:26:05.617+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='extract_curated' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T13:25:27.902476+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T13:25:27.902476+00:00'
[2025-07-19T13:26:05.620+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-07-19T13:26:05.823+0000] {python.py:201} INFO - Done. Returned value was: shape: (251, 8)
┌────────────┬────────────┬────────────┬────────────┬───────────┬──────────┬───────────┬───────────┐
│ date       ┆ close      ┆ high       ┆ low        ┆ open      ┆ volume   ┆ rsi       ┆ ema_20    │
│ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---      ┆ ---       ┆ ---       │
│ datetime[n ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ i64      ┆ f64       ┆ f64       │
│ s]         ┆            ┆            ┆            ┆           ┆          ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2024-07-17 ┆ 550.088562 ┆ 553.614651 ┆ 549.762605 ┆ 551.92566 ┆ 57119000 ┆ null      ┆ null      │
│ 00:00:00   ┆            ┆            ┆            ┆ 6         ┆          ┆           ┆           │
│ 2024-07-18 ┆ 545.861145 ┆ 552.636799 ┆ 543.658598 ┆ 551.63921 ┆ 56270400 ┆ null      ┆ null      │
│ 00:00:00   ┆            ┆            ┆            ┆ 4         ┆          ┆           ┆           │
│ 2024-07-19 ┆ 542.236328 ┆ 547.263738 ┆ 541.169597 ┆ 545.62412 ┆ 65509100 ┆ null      ┆ null      │
│ 00:00:00   ┆            ┆            ┆            ┆ 5         ┆          ┆           ┆           │
│ 2024-07-22 ┆ 547.826782 ┆ 548.43915  ┆ 544.241433 ┆ 546.19705 ┆ 43346700 ┆ null      ┆ null      │
│ 00:00:00   ┆            ┆            ┆            ┆ 6         ┆          ┆           ┆           │
│ 2024-07-23 ┆ 546.967529 ┆ 549.891077 ┆ 546.47368  ┆ 547.71812 ┆ 34439600 ┆ null      ┆ null      │
│ 00:00:00   ┆            ┆            ┆            ┆ 9         ┆          ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …        ┆ …         ┆ …         │
│ 2025-07-11 ┆ 623.619995 ┆ 624.859985 ┆ 621.530029 ┆ 622.73999 ┆ 63670200 ┆ 68.448737 ┆ 612.70272 │
│ 00:00:00   ┆            ┆            ┆            ┆           ┆          ┆           ┆ 9         │
│ 2025-07-14 ┆ 624.809998 ┆ 625.159973 ┆ 621.799988 ┆ 623.15997 ┆ 51898500 ┆ 69.31768  ┆ 613.85580 │
│ 00:00:00   ┆            ┆            ┆            ┆ 3         ┆          ┆           ┆ 2         │
│ 2025-07-15 ┆ 622.140015 ┆ 627.859985 ┆ 622.059998 ┆ 627.52002 ┆ 74317300 ┆ 64.992697 ┆ 614.64477 │
│ 00:00:00   ┆            ┆            ┆            ┆           ┆          ┆           ┆ 5         │
│ 2025-07-16 ┆ 624.219971 ┆ 624.72998  ┆ 618.049988 ┆ 623.73999 ┆ 88837200 ┆ 66.733989 ┆ 615.55669 │
│ 00:00:00   ┆            ┆            ┆            ┆           ┆          ┆           ┆ 8         │
│ 2025-07-17 ┆ 627.909973 ┆ 628.140015 ┆ 624.179993 ┆ 624.40002 ┆ 42029380 ┆ 69.62097  ┆ 616.73320 │
│ 00:00:00   ┆            ┆            ┆            ┆ 4         ┆          ┆           ┆ 1         │
└────────────┴────────────┴────────────┴────────────┴───────────┴──────────┴───────────┴───────────┘
[2025-07-19T13:26:05.828+0000] {xcom.py:664} ERROR - Object of type bytes is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-07-19T13:26:05.829+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'bytes'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 440, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
[2025-07-19T13:26:05.833+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=extract_curated, execution_date=20250719T132527, start_date=20250719T132605, end_date=20250719T132605
[2025-07-19T13:26:05.838+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 71 for task extract_curated (Object of type bytes is not JSON serializable; 364)
[2025-07-19T13:26:05.848+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T13:26:05.860+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
