[2025-07-19T14:10:29.696+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:10:25.833279+00:00 [queued]>
[2025-07-19T14:10:29.699+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:10:25.833279+00:00 [queued]>
[2025-07-19T14:10:29.699+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-19T14:10:29.702+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_features> on 2025-07-19 14:10:25.833279+00:00
[2025-07-19T14:10:29.706+0000] {standard_task_runner.py:60} INFO - Started process 415 to run task
[2025-07-19T14:10:29.708+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'build_ml_features', 'transform_features', 'manual__2025-07-19T14:10:25.833279+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/build_ml_features_dag.py', '--cfg-path', '/tmp/tmpfjx98w0a']
[2025-07-19T14:10:29.709+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask transform_features
[2025-07-19T14:10:29.724+0000] {task_command.py:423} INFO - Running <TaskInstance: build_ml_features.transform_features manual__2025-07-19T14:10:25.833279+00:00 [running]> on host f0ff35199671
[2025-07-19T14:10:29.749+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-platform' AIRFLOW_CTX_DAG_ID='build_ml_features' AIRFLOW_CTX_TASK_ID='transform_features' AIRFLOW_CTX_EXECUTION_DATE='2025-07-19T14:10:25.833279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-19T14:10:25.833279+00:00'
[2025-07-19T14:10:29.767+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/build_ml_features_dag.py", line 79, in transform_features
    df.pipe(compute_ema)
  File "/home/airflow/.local/lib/python3.8/site-packages/polars/dataframe/frame.py", line 5762, in pipe
    return function(self, *args, **kwargs)
  File "/opt/airflow/features/features_v1.py", line 49, in compute_atr
    tr = pl.concat(
AttributeError: 'Expr' object has no attribute 'max_horizontal'
[2025-07-19T14:10:29.772+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=build_ml_features, task_id=transform_features, execution_date=20250719T141025, start_date=20250719T141029, end_date=20250719T141029
[2025-07-19T14:10:29.776+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task transform_features ('Expr' object has no attribute 'max_horizontal'; 415)
[2025-07-19T14:10:29.807+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-19T14:10:29.816+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
